<a href="https://colab.research.google.com/github/eresheevaa/School-Coding-Alina-Eresheeva/blob/main/Cancer_dataset_Classification_Methods_Alina_Eresheeva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
### KNN Classification Method
#The K-nearest-neighbors (KNN) classification algorithm is based on the premise “If it walks like duck and quacks like a duck, it’s a duck.” 
#To use KNN, you provide a value for the number K that specifies the number of neighboring training set values to which a value must be similar 
#in order to be considered part of a group. 


import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

names = ['Sample', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 
         'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'class']

df = pd.read_csv('Breast.Data (1).csv', header= None, names=names)
X = np.array(df.iloc[:, 1:10])
y = np.array(df['class'])

#split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [9]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)

print('\nModel accuracy score: ', accuracy_score(y_test, pred))
print(confusion_matrix(y_test,pred))


Model accuracy score:  0.975609756097561
[[129   2]
 [  3  71]]


In [10]:
### LOGISTIC REGRESSION CLASSIFICATION ON IRIS DATASET
#The logistic regression classifier is best suited for binary-dependent variables—classifications for which there are only two classes, 
#such as gender, a tumor being malignant or benign, and so on. You can use logistic regression for multiclass problems,
#but your results may not prove as accurate as other methods. 

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix


names = ['Sample', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 
         'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'class']

df = pd.read_csv('Breast.Data (1).csv', header= None, names=names)
X = np.array(df.iloc[:, 1:10])
y = np.array(df['class'])

#split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [11]:
model = LogisticRegression(solver='lbfgs').fit(X_train,y_train)
pred = model.predict(X_test)

In [29]:
print('\nAccuracy score: ', accuracy_score(y_test, pred))
print(confusion_matrix(y_test,pred))


Accuracy score:  0.9707317073170731
[[125   5]
 [  1  74]]


In [19]:
### DECISION TREE CLASSIFICATION METHOD
# A decision tree is a graph-based data structure that a program can use to follow a series of decision paths to arrive at a decision. 
#This figure illustrates a decision tree that determines a student’s test grade.

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
import sklearn.tree as tree
from sklearn.metrics import confusion_matrix


names = ['Sample', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 
         'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'class']

df = pd.read_csv('Breast.Data (1).csv', header= None, names=names)
X = np.array(df.iloc[:, 1:10])
y = np.array(df['class'])

#split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [20]:
DT = tree.DecisionTreeClassifier()
DT.fit(X_train, y_train)
pred = DT.predict(X_test)

print('\nAccuracy score: ', accuracy_score(y_test, pred))
print('\nConfusion Matrix\n', confusion_matrix(y_test, pred))


Accuracy score:  0.9317073170731708

Confusion Matrix
 [[121   8]
 [  6  70]]


In [25]:
# Viewing the decision tree

import graphviz
from sklearn.tree import export_graphviz

export_graphviz(DT, out_file='DecisionTree.dot')

with open('DecisionTree.dot') as f:
  dot_graph = f.read()

g = graphviz.Source(dot_graph)
g.render()

print('PDF created')

PDF created


In [26]:
### RANDOM FOREST CLASSIFICATON 
# Depending on the data set and model, there may be times when the decision tree becomes very deep (many levels of nodes). 
# These decision trees will overfill the data and will have a large variance. 
# A random-forest classification model creates many different decision trees for a data set and then, based on each tree’s prediction, 
# the trees essentially vote to select the tree that produces the best result.

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
import sklearn.tree as tree
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier


names = ['Sample', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 
         'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'class']

df = pd.read_csv('Breast.Data (1).csv', header= None, names=names)
X = np.array(df.iloc[:, 1:10])
y = np.array(df['class'])

#split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [28]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)

In [32]:
print('\nAccuracy score: ', accuracy_score(y_test, pred))
print('\nConfusion matrix:\n' , confusion_matrix(y_test,pred))


Accuracy score:  0.9707317073170731

Confusion matrix:
 [[125   5]
 [  1  74]]


In [33]:
### SUPPORT VECTOR MACHINE CLASSIFYING (SVM) OR SUPPORT VECTOR CLASSIFIER (SVC)
# The support vector machine (SVM), also called an SVC (support vector classifier) classifies data by separating values with a line called a hyperplane.
# Classes that you can separate using a line are said to be linearly separable. As you can see, there are many lines you can use to divide the classes.
# The goal of SVC is to find the line that creates the widest separation between the classes. 
#To calculate the best separation line, the algorithm uses two additional lines called support vectors.

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

names = ['Sample', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 
         'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'class']

df = pd.read_csv('Breast.Data (1).csv', header= None, names=names)
X = np.array(df.iloc[:, 1:10])
y = np.array(df['class'])

#split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [35]:
model = SVC(gamma = 'auto').fit(X_train, y_train)
pred = model.predict(X_test)

print('\nModel accuracy score: ', accuracy_score(y_test,pred))


Model accuracy score:  0.9463414634146341
